import { creatorAuthTest as test, expect } from "../test-base";
import { createPromotion, deletePromotion, getPromotionId } from "@helpers/api/promotion";
import {
  formatPromotionListDate,
  generatePromotionValidationData,
  promotionValidationData,
} from "@test-data/creator/promotions.validation.data";
import { promotionsScopeData } from "@test-data/creator/promotions.scope.data";
import { promotionsAffiliateData } from "@test-data/creator/promotions.affiliate.data";
import { promotionsPricingData } from "@test-data/creator/promotions.pricing.data";
import { promotionsLifecycleData } from "@test-data/creator/promotions.lifecycle.data";
import { generatePromotionData } from "@test-data/creator/promotion.data";

const DAY_MS = 24 * 60 * 60 * 1000;

test.describe("Creator Promotions", () => {
  test("Validate Promotions Pricing, Vouchers, and Fees", {
    tag: ["@AUT-FV-237", "@promotions", "@creator", "@regression"],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(90_000);

    const savedIds: string[] = [];
    const openCreate = async () => {
      await creatorNav.open("promotions");
      await promotionsPage.openCreatePromotionForm();
    };
    const track = (response: Awaited<ReturnType<typeof promotionsPage.submitPromotionForm>>) => {
      savedIds.push(getPromotionId(response));
    };

    try {
      await test.step("Create percentage discount", async () => {
        const form = generatePromotionValidationData();
        await openCreate();
        const response = await promotionsPage.createDiscountPromotion(
          "percentage",
          { ...form, discount: promotionsPricingData.percentageDiscount },
          { voucherPattern: promotionsPricingData.voucherCodePattern },
        );
        track(response);
        promotionsPage.expectDiscountTypeSaved(response, "percentage");
        expect(response.data.discount).toBe(promotionsPricingData.percentageDiscount);
      });

      await test.step("Create fixed-amount discount", async () => {
        const form = generatePromotionValidationData();
        await openCreate();
        const response = await promotionsPage.createDiscountPromotion("fixed", {
          ...form,
          discount: promotionsPricingData.fixedDiscount,
        });
        track(response);
        promotionsPage.expectDiscountTypeSaved(response, "flat");
        expect(response.data.discount).toBe(promotionsPricingData.fixedDiscount);
      });

      await test.step("Observe auto-generated voucher code", async () => {
        await openCreate();
        await promotionsPage.expectAutoGeneratedVoucherCode(promotionsPricingData.voucherCodePattern);
      });

      await test.step("Refresh generated voucher code", async () => {
        const initialCode = await promotionsPage.expectAutoGeneratedVoucherCode(
          promotionsPricingData.voucherCodePattern,
        );
        const refreshedCode = await promotionsPage.refreshVoucherCode();
        expect(refreshedCode).not.toBe(initialCode);
        expect(refreshedCode).toMatch(promotionsPricingData.voucherCodePattern);
      });
    } finally {
      for (const promotionId of savedIds) {
        await deletePromotion(page.request, promotionId);
      }
    }
  });

  test("Validate Promotions Inputs and Boundary Conditions", {
    tag: ["@AUT-FV-236", "@promotions", "@creator", "@regression"],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    let unlimitedPromotionId = "";
    let limitedPromotionId = "";

    try {
      await test.step("Validate required fields", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.submitEmptyPromotionForm();
        await promotionsPage.expectRequiredFieldFeedback();
      });

      await test.step("Save promotion without usage limit", async () => {
        const promotion = generatePromotionValidationData({ maximumUsage: undefined });

        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(promotion);

        const response = await promotionsPage.submitPromotionForm();
        unlimitedPromotionId = getPromotionId(response);
        expect(response.data.name).toBe(promotion.name);
        expect(response.data.maxUsed).toBeNull();
      });

      await test.step("Save promotion with usage limit", async () => {
        const promotion = generatePromotionValidationData({
          maximumUsage: promotionValidationData.maximumUsage,
        });

        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(promotion);

        const response = await promotionsPage.submitPromotionForm();
        limitedPromotionId = getPromotionId(response);
        expect(response.data.name).toBe(promotion.name);
        expect(response.data.maxUsed).toBe(promotion.maximumUsage);
      });
    } finally {
      if (limitedPromotionId) {
        await deletePromotion(page.request, limitedPromotionId);
      }

      if (unlimitedPromotionId) {
        await deletePromotion(page.request, unlimitedPromotionId);
      }
    }
  });

  test("Verify Core Promotions Behavior", {
    tag: ["@AUT-FV-238", "@promotions", "@creator", "@regression"],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    await test.step("Verify default All Products scope on create form", async () => {
      await creatorNav.open("promotions");
      await promotionsPage.openCreatePromotionForm();
      await promotionsPage.expectDefaultAllProductsScope();
    });

    const promotion = generatePromotionValidationData();
    let promotionId = "";

    try {
      await test.step("Enable affiliate commission and assign creator", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(promotion);
        await promotionsPage.enableAffiliateCommission(promotionsAffiliateData.commission);
        await promotionsPage.assignAffiliateCreator(promotionsAffiliateData.assigneeSearch);
        await promotionsPage.expectAssignedAffiliateCreator(promotionsAffiliateData.assigneeHandle);
      });

      await test.step("Save and verify affiliate assignment is stored", async () => {
        const response = await promotionsPage.submitPromotionForm();
        promotionId = getPromotionId(response);
        promotionsPage.expectAffiliateAssignmentSaved(response, {
          commission: promotionsAffiliateData.commission,
          username: promotionsAffiliateData.assigneeHandle,
        });
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.expectAffiliateBadgeInList(promotion.code);
      });
    } finally {
      if (promotionId) {
        await deletePromotion(page.request, promotionId);
      }}
  });

  test("Publish & Share Promotions", {
    tag: ["@AUT-FV-244", "@promotions", "@creator", "@regression"],
    annotation: [{ type: "covers", description: "TC-PRM-C-018, TC-PRM-C-019, TC-PRM-C-020" }],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    const promotion = generatePromotionValidationData({
      discount: promotionsLifecycleData.initialDiscount,
    });
    let promotionId = "";

    try {
      await test.step("Publish promotion and verify live status", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(promotion);
        const response = await promotionsPage.submitPromotionForm();
        promotionId = getPromotionId(response);
        expect(response.data.code).toBeTruthy();

        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.expectPromotionRowFields(promotion.code, {
          name: promotion.name,
          code: promotion.code,
          discountLabel: `${promotionsLifecycleData.initialDiscount}% off`,
          status: "Active",
          redeemCount: "0",
        });
      });

      await test.step("Copy promotion share code", async () => {
        await page.context().grantPermissions(["clipboard-read", "clipboard-write"]);
        await promotionsPage.copyPromotionCode(promotion.code);
        await promotionsPage.expectPromotionCodeCopied(promotion.code);
      });

      await test.step("Display promotion in management list", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.expectLoaded();
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.expectPromotionListed(promotion.code);
      });
    } finally {
      if (promotionId) {
        await deletePromotion(page.request, promotionId);
      }
    }
  });

  test("Edit Promotions Lifecycle", {
    tag: ["@AUT-FV-245", "@promotions", "@creator", "@regression"],
    annotation: [
      { type: "covers", description: "TC-PRM-C-027, TC-PRM-C-028" },
      { type: "deferred", description: "TC-PRM-C-028 buyer redemption checks omitted (creator-side save verification only)" },
    ],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    const promotion = generatePromotionValidationData({
      discount: promotionsLifecycleData.initialDiscount,
    });
    let promotionId = "";

    try {
      await test.step("Seed live promotion for edit lifecycle", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(promotion);
        promotionId = getPromotionId(await promotionsPage.submitPromotionForm());
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
      });

      await test.step("Edit prepopulates existing configuration", async () => {
        await promotionsPage.openPromotionEdit(promotion.code, promotion.name);
        await promotionsPage.expectPromotionFormPrefilled(promotion);
      });

      await test.step("Update discount and verify saved configuration", async () => {
        await promotionsPage.updatePromotionDiscount(promotionsLifecycleData.updatedDiscount);
        const response = await promotionsPage.savePromotionEdit();
        expect(response.data.discount).toBe(promotionsLifecycleData.updatedDiscount);

        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.openPromotionEdit(promotion.code, promotion.name);
        await promotionsPage.expectPromotionFormPrefilled({
          ...promotion,
          discount: promotionsLifecycleData.updatedDiscount,
        });
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.expectPromotionRowFields(promotion.code, {
          name: promotion.name,
          code: promotion.code,
          discountLabel: `${promotionsLifecycleData.updatedDiscount}% off`,
          status: "Active",
          redeemCount: "0",
        });
      });
    } finally {
      if (promotionId) {
        await deletePromotion(page.request, promotionId);
      }
    }
  });

  test("Verify Promotion Copy Feedback and Delete Confirmation", {
    tag: ["@AUT-FV-246", "@promotions", "@creator", "@smoke", "@regression"],
    annotation: [{ type: "covers", description: "TC-PRM-C-022, TC-PRM-C-029" }],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    const hendraToken = process.env.YAPP_TEST_ACCESS_TOKEN?.replace(/"/g, "");
    test.skip(!hendraToken, "YAPP_TEST_ACCESS_TOKEN for Hendra is required");
    if (!hendraToken) return;

    const copyPromotion = generatePromotionValidationData({
      discount: promotionsLifecycleData.initialDiscount,
    });
    const deletePromotionData = generatePromotionData("active");

    let copyPromotionId = "";
    let deletePromotionId = "";

    try {
      await test.step("Seed live promotion for copy feedback", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(copyPromotion);
        copyPromotionId = getPromotionId(await promotionsPage.submitPromotionForm());
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(copyPromotion.name, copyPromotion.code);
      });

      await test.step("Copy promotion code and verify confirmation feedback", async () => {
        await page.context().grantPermissions(["clipboard-read", "clipboard-write"]);
        await promotionsPage.copyPromotionCode(copyPromotion.code);
        await promotionsPage.expectCopyConfirmationFeedback(copyPromotion.code);
        await promotionsPage.expectPromotionCodeCopied(copyPromotion.code);
      });

      await test.step("Open delete action and verify confirmation dialog before deletion", async () => {
        deletePromotionId = getPromotionId(
          await createPromotion(page.request, deletePromotionData, hendraToken),
        );
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(deletePromotionData.name, deletePromotionData.code);
        await promotionsPage.openDeleteConfirmation(deletePromotionData.code);
        await promotionsPage.expectDeleteConfirmationVisible();
        await promotionsPage.dismissDeleteConfirmation();
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(deletePromotionData.name, deletePromotionData.code);
        await promotionsPage.expectPromotionListed(deletePromotionData.code);
      });
    } finally {
      if (copyPromotionId) {
        await deletePromotion(page.request, copyPromotionId, hendraToken);
      }
      if (deletePromotionId) {
        await deletePromotion(page.request, deletePromotionId, hendraToken);
      }
    }
  });

  test("Select selected-products scope", {
    tag: ["@AUT-FV-239", "@promotions", "@creator", "@regression"],
    annotation: [{ type: "covers", description: "TC-PRM-C-009" }],
  }, async ({ creatorNav, promotionsPage }) => {
    await test.step("Open create promotion form", async () => {
      await creatorNav.open("promotions");
      await promotionsPage.openCreatePromotionForm();
    });

    await test.step("Choose Selected Products and verify product selector", async () => {
      await promotionsPage.selectSelectedProductsScope();
    });
  });

  test("Search products across categories in product scope", {
    tag: ["@AUT-FV-240", "@promotions", "@creator", "@regression"],
  }, async ({ creatorNav, promotionsPage }) => {
    test.setTimeout(120_000);

    await test.step("Open create promotion form and choose Selected Products", async () => {
      await creatorNav.open("promotions");
      await promotionsPage.openCreatePromotionForm();
      await promotionsPage.selectSelectedProductsScope();
    });

    await test.step("Search and select products from different categories", async () => {
      await promotionsPage.searchProductsInScope(promotionsScopeData.products.telegram);
      await promotionsPage.expectProductSelectableInScope(promotionsScopeData.products.telegram);
      await promotionsPage.selectProductInScope(promotionsScopeData.products.telegram);

      await promotionsPage.searchProductsInScope(promotionsScopeData.products.digitalDownload);
      await promotionsPage.expectProductSelectableInScope(promotionsScopeData.products.digitalDownload);
      await promotionsPage.selectProductInScope(promotionsScopeData.products.digitalDownload);
    });
  });

  test("Persist Promotions Changes and State", {
    tag: ["@AUT-FV-241", "@promotions", "@creator", "@regression"],
    annotation: [{ type: "covers", description: "TC-PRM-C-011" }],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    const promotion = generatePromotionValidationData();
    const selectedProducts = [
      promotionsScopeData.products.telegram,
      promotionsScopeData.products.digitalDownload,
    ];
    let promotionId = "";

    try {
      await test.step("Create promotion with selected products and save", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillSelectedProductsPromotion(promotion, selectedProducts);
        const response = await promotionsPage.submitPromotionForm();
        promotionId = getPromotionId(response);
      });

      await test.step("Reopen promotion edit and verify selected products are prepopulated", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.openPromotionEdit(promotion.code, promotion.name);
        await promotionsPage.expectSelectedProductsOnEdit(selectedProducts);
      });
    } finally {
      if (promotionId) {
        await deletePromotion(page.request, promotionId);
      }
    }
  });

  test("Validate Promotions Scheduling, Availability, and Time Rules", {
    tag: ["@AUT-FV-242", "@promotions", "@creator", "@regression"],
    annotation: [{ type: "covers", description: "TC-PRM-C-012" }],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    const startDate = new Date();
    const endDate = new Date(Date.now() + DAY_MS);
    const promotion = generatePromotionValidationData({
      startDateDay: `${startDate.getMonth() + 1}/${startDate.getDate()}/${startDate.getFullYear()}`,
      endDateDay: `${endDate.getMonth() + 1}/${endDate.getDate()}/${endDate.getFullYear()}`,
    });
    let promotionId = "";

    try {
      await test.step("Create promotion with start and end period then save", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.openCreatePromotionForm();
        await promotionsPage.fillPromotionForm(promotion);
        const response = await promotionsPage.submitPromotionForm();
        promotionId = getPromotionId(response);
      });

      await test.step("Verify saved promotion period on management list", async () => {
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(promotion.name, promotion.code);
        await promotionsPage.expectPromotionPeriodInList(
          promotion.code,
          formatPromotionListDate(startDate),
          formatPromotionListDate(endDate),
        );
      });
    } finally {
      if (promotionId) {
        await deletePromotion(page.request, promotionId);
      }
    }
  });

  test("Verify Promotions Access, Entitlements, and Eligibility", {
    tag: ["@AUT-FV-243", "@promotions", "@creator", "@smoke", "@regression"],
  }, async ({ creatorNav, promotionsPage, page }) => {
    test.setTimeout(120_000);

    const hendraToken = process.env.YAPP_TEST_ACCESS_TOKEN?.replace(/"/g, "");
    test.skip(!hendraToken, "YAPP_TEST_ACCESS_TOKEN for Hendra is required");
    if (!hendraToken) return;

    const listPromotion = generatePromotionData("active");
    const deletePromotionData = generatePromotionData("active");

    let listPromotionId = "";

    try {
      await test.step("Display promotion list fields", async () => {
        listPromotionId = getPromotionId(
          await createPromotion(page.request, listPromotion, hendraToken),
        );
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(listPromotion.name, listPromotion.code);
        await promotionsPage.expectPromotionRowFields(listPromotion.code, {
          name: listPromotion.name,
          code: listPromotion.code,
          discountLabel: `${listPromotion.discount}% off`,
          status: "Active",
          redeemCount: "0",
        });
        await promotionsPage.expectPromotionPeriodInList(
          listPromotion.code,
          formatPromotionListDate(new Date(listPromotion.periodStartAt)),
          formatPromotionListDate(new Date(listPromotion.periodEndAt)),
        );
      });

      await test.step("Delete promotion from management list", async () => {
        await createPromotion(page.request, deletePromotionData, hendraToken);
        await creatorNav.open("promotions");
        await promotionsPage.searchPromotions(deletePromotionData.name, deletePromotionData.code);
        await promotionsPage.deletePromotionFromList(deletePromotionData.code);
        await promotionsPage.expectPromotionAbsent(deletePromotionData.code);
      });
    } finally {
      if (listPromotionId) {
        await deletePromotion(page.request, listPromotionId, hendraToken);
      }
    }
  });
});
